export interface NetRoom {
  label: string;
  area: string;
}

export interface ApartmentType {
  id: string;
  category: "1+1" | "2+1" | "3+1" | "4+1 DUBLEKS";
  name: string;
  grossArea: string; // e.g. "52.50 m²"
  block: string;     // e.g. "A/C/E Blok"
  floor: string;     // e.g. "Zemin–7. Kat"
  count: string;     // e.g. "45 Adet"
  image: string;     // e.g. "/images/plans/1plus1-a.jpg"
  netRooms: NetRoom[];
}

export const APARTMENT_CATEGORIES = [
  "1+1",
  "2+1",
  "3+1",
  "4+1 DUBLEKS",
] as const;

export type ApartmentCategory = (typeof APARTMENT_CATEGORIES)[number];

export const APARTMENT_TYPES: ApartmentType[] = [
  // ─── 1+1 ───────────────────────────────────────────────────────────────────
  {
    id: "1plus1-a",
    category: "1+1",
    name: "1+1 Tip A",
    grossArea: "52.50 m²",
    block: "A/C/E Blok",
    floor: "Zemin–7. Kat",
    count: "45 Adet",
    image: "/images/plans/1plus1-a.jpg",
    netRooms: [
      { label: "Antre", area: "5.20 m²" },
      { label: "Oturma + Mutfak", area: "19.40 m²" },
      { label: "Banyo", area: "3.00 m²" },
      { label: "Yatak Odası", area: "11.50 m²" },
      { label: "Balkon", area: "5.95 m²" },
    ],
  },
  {
    id: "1plus1-b",
    category: "1+1",
    name: "1+1 Tip B",
    grossArea: "58.00 m²",
    block: "A/C/E Blok",
    floor: "1–7. Kat",
    count: "42 Adet",
    image: "/images/plans/1plus1-b.jpg",
    netRooms: [
      { label: "Antre", area: "4.40 m²" },
      { label: "Oturma + Mutfak", area: "18.50 m²" },
      { label: "Banyo", area: "4.20 m²" },
      { label: "Yatak Odası", area: "10.90 m²" },
      { label: "Balkon", area: "5.90 m²" },
    ],
  },
  {
    id: "1plus1-c",
    category: "1+1",
    name: "1+1 Tip C",
    grossArea: "53.50 m²",
    block: "A/C/E Blok",
    floor: "Zemin",
    count: "3 Adet",
    image: "/images/plans/1plus1-c.jpg",
    netRooms: [
      { label: "Antre", area: "5.70 m²" },
      { label: "Oturma + Mutfak", area: "23.20 m²" },
      { label: "Banyo", area: "3.75 m²" },
      { label: "Yatak Odası", area: "12.70 m²" },
      { label: "Balkon", area: "5.90 m²" },
    ],
  },
  {
    id: "1plus1-d",
    category: "1+1",
    name: "1+1 Tip D",
    grossArea: "66.50 m²",
    block: "A/C/E Blok",
    floor: "Zemin",
    count: "3 Adet",
    image: "/images/plans/1plus1-d.jpg",
    netRooms: [
      { label: "Antre", area: "4.60 m²" },
      { label: "Oturma + Mutfak", area: "22.50 m²" },
      { label: "Banyo", area: "4.00 m²" },
      { label: "Yatak Odası", area: "15.10 m²" },
      { label: "Balkon 1", area: "5.80 m²" },
      { label: "Balkon 2", area: "5.95 m²" },
    ],
  },
  {
    id: "1plus1-e",
    category: "1+1",
    name: "1+1 Tip E",
    grossArea: "60.50 m²",
    block: "A/B/E Blok",
    floor: "Zemin",
    count: "8 Adet",
    image: "/images/plans/1plus1-e.jpg",
    netRooms: [
      { label: "Antre", area: "6.00 m²" },
      { label: "Oturma + Mutfak", area: "21.50 m²" },
      { label: "Banyo", area: "4.20 m²" },
      { label: "Yatak Odası", area: "9.60 m²" },
      { label: "Balkon 1", area: "5.30 m²" },
      { label: "Balkon 2", area: "5.65 m²" },
    ],
  },

  // ─── 2+1 ───────────────────────────────────────────────────────────────────
  {
    id: "2plus1-a",
    category: "2+1",
    name: "2+1 Tip A",
    grossArea: "93.20 m²",
    block: "A/B/E Blok",
    floor: "1–7. Kat",
    count: "52 Adet",
    image: "/images/plans/2plus1-a.jpg",
    netRooms: [
      { label: "Antre", area: "3.90 m²" },
      { label: "Oturma + Mutfak", area: "27.60 m²" },
      { label: "Hol", area: "3.60 m²" },
      { label: "Banyo", area: "4.30 m²" },
      { label: "Yatak Odası", area: "11.00 m²" },
      { label: "Ebeveyn Yatak Odası", area: "15.70 m²" },
      { label: "Ebeveyn Banyosu", area: "2.85 m²" },
      { label: "Balkon 1", area: "4.30 m²" },
      { label: "Balkon 2", area: "9.00 m²" },
    ],
  },
  {
    id: "2plus1-b",
    category: "2+1",
    name: "2+1 Tip B",
    grossArea: "82.50 m²",
    block: "A/B/C-D/E Blok",
    floor: "Zemin–7. Kat",
    count: "200 Adet",
    image: "/images/plans/2plus1-b.jpg",
    netRooms: [
      { label: "Antre", area: "5.20 m²" },
      { label: "Oturma + Mutfak", area: "22.95 m²" },
      { label: "Hol", area: "3.50 m²" },
      { label: "Banyo", area: "3.50 m²" },
      { label: "Yatak Odası", area: "9.70 m²" },
      { label: "Ebeveyn Yatak Odası", area: "11.60 m²" },
      { label: "Ebeveyn Banyosu", area: "3.50 m²" },
      { label: "Balkon 1", area: "3.80 m²" },
      { label: "Balkon 2", area: "7.50 m²" },
    ],
  },
  {
    id: "2plus1-c",
    category: "2+1",
    name: "2+1 Tip C",
    grossArea: "100.20 m²",
    block: "D Blok (Köşe)",
    floor: "Zemin–7. Kat",
    count: "8 Adet",
    image: "/images/plans/2plus1-c.jpg",
    netRooms: [
      { label: "Antre + Hol", area: "9.80 m²" },
      { label: "Oturma + Mutfak", area: "34.80 m²" },
      { label: "Yatak Odası", area: "10.65 m²" },
      { label: "Banyo", area: "5.10 m²" },
      { label: "Ebeveyn Banyosu", area: "4.30 m²" },
      { label: "Ebeveyn Odası", area: "14.90 m²" },
      { label: "Balkon 1", area: "3.90 m²" },
      { label: "Balkon 2", area: "4.80 m²" },
    ],
  },
  {
    id: "2plus1-d",
    category: "2+1",
    name: "2+1 Tip D",
    grossArea: "86.50 m²",
    block: "C Blok",
    floor: "Zemin",
    count: "5 Adet",
    image: "/images/plans/2plus1-d.jpg",
    netRooms: [
      { label: "Antre", area: "3.10 m²" },
      { label: "Oturma + Mutfak", area: "21.60 m²" },
      { label: "Hol", area: "3.30 m²" },
      { label: "WC + Banyo", area: "4.30 m²" },
      { label: "Yatak Odası", area: "10.20 m²" },
      { label: "Ebeveyn Yatak Odası", area: "11.15 m²" },
      { label: "Balkon 1", area: "3.50 m²" },
      { label: "Balkon 2", area: "6.00 m²" },
    ],
  },
  {
    id: "2plus1-e",
    category: "2+1",
    name: "2+1 Tip E",
    grossArea: "71.92 m²",
    block: "C Blok",
    floor: "Zemin",
    count: "1 Adet",
    image: "/images/plans/2plus1-e.jpg",
    netRooms: [
      { label: "Antre", area: "4.16 m²" },
      { label: "Oturma + Mutfak", area: "26.10 m²" },
      { label: "Hol", area: "3.95 m²" },
      { label: "WC + Banyo", area: "4.15 m²" },
      { label: "Yatak Odası", area: "11.25 m²" },
      { label: "Ebeveyn Yatak Odası", area: "14.10 m²" },
      { label: "Balkon 1", area: "5.75 m²" },
      { label: "Balkon 2", area: "5.85 m²" },
    ],
  },

  // ─── 3+1 ───────────────────────────────────────────────────────────────────
  {
    id: "3plus1-a",
    category: "3+1",
    name: "3+1 Tip A",
    grossArea: "105.00 m²",
    block: "A/B/C/D Blok",
    floor: "Zemin–7. Kat",
    count: "31 Adet",
    image: "/images/plans/3plus1-a.jpg",
    netRooms: [
      { label: "Antre", area: "4.85 m²" },
      { label: "Oturma + Mutfak", area: "26.85 m²" },
      { label: "Hol", area: "5.20 m²" },
      { label: "WC", area: "2.05 m²" },
      { label: "Banyo", area: "3.95 m²" },
      { label: "Yatak Odası 1", area: "9.15 m²" },
      { label: "Yatak Odası 2", area: "9.15 m²" },
      { label: "Ebeveyn Yatak Odası", area: "13.50 m²" },
      { label: "Ebeveyn Banyosu", area: "3.05 m²" },
      { label: "Balkon 1", area: "2.96 m²" },
      { label: "Balkon 2", area: "9.20 m²" },
    ],
  },
  {
    id: "3plus1-b",
    category: "3+1",
    name: "3+1 Tip B",
    grossArea: "157.30 m²",
    block: "D Blok (Köşe)",
    floor: "Zemin–7. Kat",
    count: "8 Adet",
    image: "/images/plans/3plus1-b.jpg",
    netRooms: [
      { label: "Antre", area: "9.20 m²" },
      { label: "Oturma + Mutfak", area: "36.30 m²" },
      { label: "Balkon 1", area: "10.50 m²" },
      { label: "WC", area: "2.05 m²" },
      { label: "Hol", area: "14.30 m²" },
      { label: "Banyo", area: "4.40 m²" },
      { label: "Yatak Odası 1", area: "11.05 m²" },
      { label: "Yatak Odası 2", area: "11.05 m²" },
      { label: "Balkon 2", area: "6.07 m²" },
      { label: "Ebeveyn Yatak Odası", area: "20.80 m²" },
      { label: "Giyinme Odası", area: "8.15 m²" },
      { label: "Ebeveyn Banyosu", area: "5.10 m²" },
    ],
  },
  {
    id: "3plus1-dubleks-a",
    category: "3+1",
    name: "3+1 Dubleks Tip A",
    grossArea: "143.50 m²",
    block: "A Blok",
    floor: "Zemin",
    count: "2 Adet",
    image: "/images/plans/3plus1-dubleks-a.jpg",
    netRooms: [
      { label: "Antre", area: "4.25 m²" },
      { label: "Oturma Odası", area: "15.70 m²" },
      { label: "Mutfak", area: "14.80 m²" },
      { label: "WC", area: "1.35 m²" },
      { label: "Balkon 1", area: "5.95 m²" },
      { label: "Balkon 2", area: "4.85 m²" },
      { label: "Hol", area: "3.70 m²" },
      { label: "Yatak Odası 1", area: "10.70 m²" },
      { label: "Yatak Odası 2", area: "11.60 m²" },
      { label: "Ebeveyn Yatak Odası", area: "22.60 m²" },
      { label: "Ebeveyn Banyosu", area: "3.90 m²" },
      { label: "Banyo", area: "3.75 m²" },
      { label: "Balkon 3", area: "5.95 m²" },
      { label: "Balkon 4", area: "4.00 m²" },
    ],
  },

  // ─── 4+1 DUBLEKS ───────────────────────────────────────────────────────────
  {
    id: "4plus1-dubleks-a",
    category: "4+1 DUBLEKS",
    name: "4+1 Dubleks Tip A",
    grossArea: "211.00 m²",
    block: "A Blok",
    floor: "Zemin",
    count: "1 Adet",
    image: "/images/plans/4plus1-dubleks-a.jpg",
    netRooms: [
      { label: "Antre", area: "7.45 m²" },
      { label: "Oturma Odası", area: "27.50 m²" },
      { label: "Balkon 1", area: "8.45 m²" },
      { label: "Mutfak", area: "11.75 m²" },
      { label: "Hol 1", area: "5.00 m²" },
      { label: "WC", area: "2.30 m²" },
      { label: "Yatak Odası 1", area: "13.80 m²" },
      { label: "Yatak Odası Banyosu 1", area: "5.20 m²" },
      { label: "Balkon 2", area: "2.95 m²" },
      { label: "Hol 2", area: "8.25 m²" },
      { label: "Yatak Odası 2", area: "11.50 m²" },
      { label: "Yatak Odası Banyosu 2", area: "3.05 m²" },
      { label: "Balkon 3", area: "3.00 m²" },
      { label: "Banyo", area: "4.00 m²" },
      { label: "Yatak Odası 3", area: "10.80 m²" },
      { label: "Yatak Odası 4", area: "30.00 m²" },
      { label: "Yatak Odası Banyosu 3", area: "5.20 m²" },
      { label: "Balkon 4", area: "8.45 m²" },
    ],
  },
  {
    id: "4plus1-dubleks-b",
    category: "4+1 DUBLEKS",
    name: "4+1 Dubleks Tip B",
    grossArea: "187.00 m²",
    block: "A/B/E Blok",
    floor: "Zemin",
    count: "8 Adet",
    image: "/images/plans/4plus1-dubleks-b.jpg",
    netRooms: [
      { label: "Antre", area: "4.50 m²" },
      { label: "Oturma + Mutfak", area: "26.85 m²" },
      { label: "Balkon 1", area: "8.75 m²" },
      { label: "Hol 1", area: "5.00 m²" },
      { label: "Banyo 1", area: "3.85 m²" },
      { label: "Yatak Odası 1", area: "17.60 m²" },
      { label: "Yatak Odası Banyosu 1", area: "3.90 m²" },
      { label: "Balkon 2", area: "4.30 m²" },
      { label: "Hol 2", area: "5.70 m²" },
      { label: "Banyo 2", area: "3.85 m²" },
      { label: "Yatak Odası 2", area: "9.20 m²" },
      { label: "Yatak Odası 3", area: "20.20 m²" },
      { label: "Yatak Odası 4", area: "13.20 m²" },
      { label: "Yatak Odası Banyosu 2", area: "3.90 m²" },
      { label: "Balkon 3", area: "4.30 m²" },
      { label: "Balkon 4", area: "8.75 m²" },
    ],
  },
];
